#ifndef CCERROR_H
#define CCERROR_H

#ifndef DLLEXPORT
#define DLLEXPORT __declspec(dllexport)
#endif

#define CC_SUCCESS 1
#define NULL_LAT_IN -4
#define NULL_LAT_OUT -3
#define NULL_LON_IN -6
#define NULL_LON_OUT -5
#define NULL_NORTH_IN -8
#define NULL_NORTH_OUT -7
#define NULL_EAST_IN -10
#define NULL_EAST_OUT -9
#define NULL_KP -11
#define NULL_CONV -12

#define BAD_INPUT_UNIT_SPECIFIED -19
#define BAD_OUTPUT_UNIT_SPECIFIED -20
#define NULL_UNIT_FUNCTION -14

#define BAD_GRIDS83_OPT -1
#define BAD_SP83_ZONE -2
#define NULL_GRIDS83_FUNCTION -13
#define NULL_GRIDS83_CONST_STRUCT -15
#define NULL_LAM83_CONST_STRUCT -16
#define NULL_TM83_CONST_STRUCT -17
#define NULL_OM83_CONST_STRUCT -18

#define BAD_GRIDS27_OPT -21
#define BAD_SP27_ZONE -22
#define NULL_SP27_CONST_STRUCT -23
#define NULL_GRIDS27_FUNCTION -24

#define CANNOT_OPEN_AREALIST_FILE -27

#define NULL_VERTCON_AREA_COUNT -25
#define VERTCON_AREA_COUNT_ZERO_OR_LESS -26
#define NULL_VERTCON_GHT -28
#define VERTCON_OB -29

#define NULL_GEOID_AREA_COUNT -30
#define GEOID_AREA_COUNT_ZERO_OR_LESS -31
#define NULL_GEOID_GHT -32
#define GEOID_OB -33
#define NULL_GEOID_DATA_STRUCT -34
#define BAD_GEOID_DATA_STRUCT_FP -35

#define NULL_GEOID99_AREA_COUNT -36
#define GEOID99_AREA_COUNT_ZERO_OR_LESS -37
#define NULL_GEOID99_GHT -38
#define GEOID99_OB -39
#define NULL_GEOID99_DATA_STRUCT -40
#define BAD_GEOID99_DATA_STRUCT_FP -41

#define NULL_STD_NADCON_AREA_COUNT -50
#define STD_NADCON_AREA_COUNT_ZERO_OR_LESS -51
#define NULL_FP_LAS -52
#define NULL_FP_LOS -53
#define NADCON_OB -54
#define NULL_NADCON_DATA_STRUCT -55
#define NULL_XPT1 -56
#define NULL_YPT1 -57
#define NULL_XPT2 -58
#define NULL_YPT2 -59
#define NULL_DLAS -60
#define NULL_DLOS -61
#define CANNOT_OPEN_LASLOS_FILES -62
#define LASLOS_HEADER_NC_UNEQUAL -63
#define LASLOS_HEADER_NR_UNEQUAL -64
#define LASLOS_HEADER_XO_UNEQUAL -65
#define LASLOS_HEADER_DX_UNEQUAL -66
#define LASLOS_HEADER_YO_UNEQUAL -67
#define LASLOS_HEADER_DY_UNEQUAL -68
#define NADCON_ITERATIONS_EXCEEDED -69

#define BAD_INPUT_SYSTEM_SPECIFIED -70
#define BAD_INPUT_DATUM_SPECIFIED -71
#define BAD_INPUT_UNITS_SPECIFIED -72
#define BAD_OUTPUT_SYSTEM_SPECIFIED -73
#define BAD_OUTPUT_DATUM_SPECIFIED -74
#define BAD_OUTPUT_UNITS_SPECIFIED -75

#define BAD_INPUT_VDATUM_SPECIFIED -81
#define BAD_INPUT_VUNITS_SPECIFIED -82
#define BAD_OUTPUT_VDATUM_SPECIFIED -83
#define BAD_OUTPUT_VUNITS_SPECIFIED -84

#define BAD_GEOID_CODE_BASE_SPECIFIED -80

#define DELIMITER_IS_NULL -90
#define BAD_XIN_PARSE_FIELD_SPECIFIED -91
#define BAD_YIN_PARSE_FIELD_SPECIFIED -92
#define BAD_ZIN_PARSE_FIELD_SPECIFIED -93
#define BAD_USNGIN_PARSE_FIELD_SPECIFIED -94
#define BAD_XIN_FIELD_WIDTH_SPECIFIED -95
#define BAD_YIN_FIELD_WIDTH_SPECIFIED -96
#define BAD_XOUT_FIELD_WIDTH_SPECIFIED -97
#define BAD_YOUT_FIELD_WIDTH_SPECIFIED -98
#define BAD_POINT_NAME_IN_PARSE_FIELD_SPECIFIED -99

#define BAD_VALUE_CODE_SPECIFIED -100

#define INPUT_LINE_IS_NULL -110
#define INPUT_LINE_NOT_PARSED -111
#define INPUT_FIELD_X_COULD_NOT_BE_PARSED -112
#define INPUT_FIELD_Y_COULD_NOT_BE_PARSED -113
#define INPUT_FIELD_Z_COULD_NOT_BE_PARSED -114
#define INPUT_FIELD_POINT_NAME_COULD_NOT_BE_PARSED -115

#define NULL_OUTPUT_LINE_FORMAT_STRING -117
#define BAD_OUTPUT_LINE_FORMAT_STRING -118

#define BAD_FIELD_SPECIFIED -130
#define KEY_NOT_FOUND -131
#define CANT_OPEN_CONFIG_SCRIPT_FILE -132

#define NO_GEOID_FUNCTION_SPECIFIED -140
#define NO_VERTCON_FUNCTION_SPECIFIED -141
#define CANNOT_CALCULATE_CF -142

#define USNG_IN_STRING_NULL -200
#define USNG_IN_STRING_BAD_LENGTH -201
#define USNG_IN_STRING_BAD_GZD_COL -202
#define USNG_IN_STRING_BAD_GZD_ROW -203
#define USNG_IN_STRING_BAD_SID_COL -204
#define USNG_IN_STRING_BAD_SID_ROW -205
#define USNG_IN_STRING_BAD_EAST -206
#define USNG_IN_STRING_BAD_NORTH -207
#define USNG_IN_STRING_CANNOT_CALCULATE_NORTH_MIN -208
#define USNG_IN_CANNOT_CONVERT_USNG83_TO_GEO83 -209
#define USNG_IN_CANNOT_CONVERT_USNG27_TO_GEO27 -210
#define USNG_OUT_CANNOT_CONVERT_GEO83_TO_USNG83 -211
#define USNG_OUT_CANNOT_CONVERT_GEO27_TO_USNG27 -212
#define USNG_OUT_BAD_DIGITS_SPECIFIED -213
#define USNG_OUT_BAD_LAT -214

DLLEXPORT int _stdcall GetErrorMessage(int err_code, char *msg);

#endif